---
- name: "hadoop slavenode setup"
  block:
    - name: "copy jdk file"
      copy:
          src: "jdk-8u171-linux-x64.rpm"
          dest: "{{ pkg_path }}"
    - name: "copy hadoop file"
      copy:
          src: "hadoop-1.2.1-1.x86_64.rpm"
          dest: "{{ pkg_path }}"
    - name: "install jdk..."
      yum:
          name: "{{ pkg_path }}/jdk-8u171-linux-x64.rpm"
          state: present
          disablerepo: yes
          disable_gpg_check: yes
    - name: "installing hadoop..."
      command: "rpm -i {{ pkg_path }}/hadoop-1.2.1-1.x86_64.rpm --force"
      ignore_errors: true
    - name: "deleting exist {{ slave_path }} directory"
      file:
          path: "{{ slave_path }}"
          state: absent
    - name: "creating a new {{ slave_path }} directory"
      file:
          path: "{{ slave_path }}"
          state: directory
    - name: "configuring hdfs file..."
      template:
          src: "hdfs-site.xml.j2"
          dest: "/etc/hadoop/hdfs-site.xml"
    - name: "configuring core file..."
      template:
          src: "core-site.xml.j2"
          dest: "/etc/hadoop/core-site.xml"
    - name: "starting Datanode..."
      shell: "hadoop-daemon.sh stop datanode && hadoop-daemon.sh start datanode"
    - name: "checking status.."
      command: "jps"
      register: status
    - name: "Datanode status"
      debug:
          msg: "{{ status.stdout_lines }}"
  rescue:
    - name:
      debug:
          msg: "It look lokes your master/Name node is not ready or have any firewalld security enabled.
          Please make master node ready or disable firewalld security on both nodes then restart datanode again or run this again..."